### ISSUE TITLE
Examples needed for Play 2.8.x Template Constraints

### ISSUE THREAD

**Issue by c-lee8** [schaloner/deadbolt-2-java#113]
Hi Steve,

According to the Guide https://deadbolt-java.readme.io/docs/template-constraints

We should include these lines in the view template:

```
@import be.objectify.deadbolt.java.views.html.di.{subjectPresent, subjectPresentOr}

@subjectPresent() {
    This content will be present if handler#getSubject results in a Some 
}

@subjectPresentOr() {
    This content will be present if handler#getSubject results in a Some 
} {
  fallback content
}
```

However this resulted in 

```
play.sbt.PlayExceptions$CompilationException: Compilation error[not found: value subjectPresent]
        at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:34)
        at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:34)
        at scala.Option.map(Option.scala:230)
        at play.sbt.run.PlayReload$.$anonfun$taskFailureHandler$8(PlayReload.scala:131)
        at scala.Option.map(Option.scala:230)
        at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:104)
        at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:38)
        at play.sbt.run.PlayReload$.$anonfun$compile$3(PlayReload.scala:156)
        at scala.util.Either$LeftProjection.map(Either.scala:573)
        at play.sbt.run.PlayReload$.compile(PlayReload.scala:156)
```

Am I missing some dependencies? I am able to set up the Controller constraints. Perhaps the issue is Dependency Injection related?

I am using
`libraryDependencies += "be.objectify" %% "deadbolt-java" % "2.8.1"`

on Play Framework 2.8.8

Thank you

**Comment by c-lee8** [comment]
Ok I found the issue #45  which answered what I was looking for in the closed issues, thanks.

Essentially I needed to use Dependency Injection to put the constraints into the template

https://www.playframework.com/documentation/2.8.x/JavaTemplatesDependencyInjection
