### ISSUE TITLE
Problems when upgrading to Play 2.4.x

### ISSUE THREAD

**Issue by johdah** [schaloner/deadbolt-2-java#13]
I am not sure if this is a problem with Deadbolt. Probably it's something with my code. But I get the following errors when I annotate an action (let's say Application.about)  with SubjectPresent but not if i remove that annotation. Every time I hit refresh it's a different error but always one of these three.

[IllegalStateException: EntityManager is closed]
[PersistenceException: org.hibernate.SessionException: Session is closed!]
[RuntimeException: No EntityManager found in the context. Try to annotate your action method with @play.db.jpa.Transactional]

I have added a comment in all my Deadbolt methods and the only method that is executed is "MyDeadboltHandler.getSubject". When I have the annotation this method is executed once but when i remove the annotation it is executed several times. So it feels like the getSubject method should be OK.

```java
public F.Promise<Optional<Subject>> getSubject(Http.Context context) {
        Logger.error("MyDeadboltHandler.getSubject");
        return F.Promise.promise(() -> Optional.ofNullable(User.authenticate(Application.getCurrentSessionId().orElse(null)).get()));
}
```

I could replace the last line with

```java
return F.Promise.promise(() -> JPA.withTransaction(() -> Optional.ofNullable(User.authenticate(Application.getCurrentSessionId().orElse(null)).get())));
```

But then the code in the about action wouldn't be able to access the EntityManager.

**Comment by schaloner** [comment]
What happens if you make your `getSubject` blocking?

    public F.Promise<Optional<Subject>> getSubject(Http.Context context) {
        Logger.error("MyDeadboltHandler.getSubject");
        final Subject subject = User.authenticate...
        return F.Promise.pure(Optional.ofNullable(subject));
    }

I can't help feeling that JPA and non-blocking code don't go together...

**Comment by johdah** [comment]
It still doesn't work. Could it be that you use non-blocking in the library?

```
Caused by: java.lang.RuntimeException: No EntityManager found in the context. Try to annotate your action method with @play.db.jpa.Transactional
	at play.db.jpa.JPA.em(JPA.java:69) ~[play-java-jpa_2.11-2.4.2.jar:2.4.2]
	at dao.AbstractDAO.<init>(AbstractDAO.java:49) ~[classes/:na]
	at dao.UserDAO.<init>(UserDAO.java:29) ~[classes/:na]
	at models.User.authenticate(User.java:161) ~[classes/:na]
	at auth.MyDeadboltHandler.getSubject(MyDeadboltHandler.java:71) ~[classes/:na]
	at be.objectify.deadbolt.java.cache.DefaultSubjectCache.apply(DefaultSubjectCache.java:53) ~[deadbolt-java_2.11-2.4.0.jar:2.4.0]
	at be.objectify.deadbolt.java.cache.DefaultSubjectCache.apply(DefaultSubjectCache.java:17) ~[deadbolt-java_2.11-2.4.0.jar:2.4.0]
	at be.objectify.deadbolt.java.actions.AbstractDeadboltAction.getSubject(AbstractDeadboltAction.java:182) ~[deadbolt-java_2.11-2.4.0.jar:2.4.0]
	at be.objectify.deadbolt.java.actions.AbstractSubjectAction$SubjectTest.lambda$apply$17(AbstractSubjectAction.java:100) ~[deadbolt-java_2.11-2.4.0.jar:2.4.0]
	at be.objectify.deadbolt.java.actions.AbstractSubjectAction$SubjectTest$$Lambda$58/302975058.get(Unknown Source) ~[na:na]
	at java.util.Optional.orElseGet(Optional.java:267) ~[na:1.8.0_45]
	at be.objectify.deadbolt.java.actions.AbstractSubjectAction$SubjectTest.apply(AbstractSubjectAction.java:100) ~[deadbolt-java_2.11-2.4.0.jar:2.4.0]
	at be.objectify.deadbolt.java.actions.AbstractSubjectAction.lambda$execute$15(AbstractSubjectAction.java:74) ~[deadbolt-java_2.11-2.4.0.jar:2.4.0]
	at be.objectify.deadbolt.java.actions.AbstractSubjectAction$$Lambda$56/106813750.apply(Unknown Source) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:106) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:106) ~[play_2.11-2.4.2.jar:2.4.2]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) [scala-library-2.11.7.jar:na]
	... 9 common frames omitted
```

**Comment by schaloner** [comment]
The only part of Deadbolt that's blocking is the templates, because the promises have to be completed in sequence for templates to be rendered correctly.  Apart from that, everything is non-blocking.

Are you statically calling `JPA.em()` (it looks like it, from the stack trace)?  If so, what happens if you inject `JPAApi ` and use that instead?

**Comment by johdah** [comment]
I haven't managed to get it to work. I keep getting a Null Pointer Exception when I try to inject JPAApi

```java
public abstract class AbstractDAO<T extends AbstractModel, M extends AbstractModel_> {
    protected final Class<T> classType;
//    protected final M metaclass;
    protected final EntityManager em;
    protected final CriteriaBuilder cb;

    @Inject
    JPAApi jpa;

    /**
     * @param classType e.g. User.class
     * @param metaType e.g. User_.class
     */
    protected AbstractDAO(Class<T> classType, Class<M> metaType) {
//        this.em = JPA.em();
        this.em = jpa.em("default");
        this.cb = em.getCriteriaBuilder();
        this.classType = classType;
    }
}
```

**Comment by schaloner** [comment]
I suspect your constructor is being called before the field injection.  Personally, I aim to always use constructor injection so that's one approach you can take.

Alternatively, you can use a provider to inject result of `jpa.em("default")` into your DAOs.

**Comment by johdah** [comment]
How would I do that without causing a compiler error for "actual and formal argument lists differ in length". I still need my classType argument

**Comment by schaloner** [comment]
Injections occur in sub-classes and are passed into the super class.

    public abstract class AbstractDAO<T extends AbstractModel, M extends AbstractModel_> {
        protected final Class<T> classType;
    //    protected final M metaclass;
        protected final EntityManager em;
        protected final CriteriaBuilder cb;

        /**
         * @param jpaApi Play JPA support 
         * @param classType e.g. User.class
         * @param metaType e.g. User_.class
         */
        protected AbstractDAO(final JPAApi jpaApi,
                              final Class<T> classType, 
                              final Class<M> metaType) {
            this.em = jpaApi.em("default");
            this.cb = em.getCriteriaBuilder();
            this.classType = classType;
        }
    }

    public class UserDAO extends AbstractDAO<User, User_> {

        @Inject
        public UserDAO(final JPAApi jpaApi) {
            super(jpaApi, 
                  User.class, 
                  User_.class);
        }
    }

**Comment by johdah** [comment]
I will test that, but how do i create an instance. I still have to pass something for the arguments?

If I want to write new UserDAO(...)

**Comment by schaloner** [comment]
You have a couple of options:

1. Have a single DAO injected into your controller
2. Get an instance of the DAO from the injector, e.g. `play.Play.application().injector().instanceOf(UserDao.class)`

**Comment by johdah** [comment]
Nice, I got this error now. Do you think this has to do with Deadbolt? I don't really understand whats causing this error.

```
2015-07-13 22:30:44,728 - [error] b.o.d.j.ViewSupport - Timeout when attempting to complete future within [1000]ms.  Denying access to resource.
play.libs.F$PromiseTimeoutException: Futures timed out after [1000 milliseconds]
	at play.core.j.FPromiseHelper$.get(FPromiseHelper.scala:57) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.core.j.FPromiseHelper.get(FPromiseHelper.scala) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.libs.F$Promise.get(F.java:282) ~[play_2.11-2.4.2.jar:2.4.2]
	at be.objectify.deadbolt.java.ViewSupport.viewPattern(ViewSupport.java:238) ~[deadbolt-java_2.11-2.4.0.jar:2.4.0]
	at be.objectify.deadbolt.java.views.html.pattern_Scope0$pattern_Scope1$pattern.apply(pattern.template.scala:40) [deadbolt-java_2.11-2.4.0.jar:2.4.0]
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [1000 milliseconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219) ~[scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223) ~[scala-library-2.11.7.jar:na]
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190) ~[scala-library-2.11.7.jar:na]
	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:169) ~[akka-actor_2.11-2.3.11.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640) [scala-library-2.11.7.jar:na]
2015-07-13 22:30:44,728 - [error] a.MyDeadboltTemplateFailureListener - Template constraint failure: message [Error when checking view constraint: Futures timed out after [1000 milliseconds]]  timeout [1000]ms
```

**Comment by schaloner** [comment]
This is happening because it's taking longer than 1000ms for `DeadboltHandler#getSubject` to complete with an option (either Some or None, it doesn't matter).

Things you can do:

**Increase the global timeout ìn the config**

For example, 

    deadbolt {
        java {
            view-timeout=2000
        }
    }

This is not a fix, however - if the DB latency increases, you'll hit the same problem.

**Enable per-request caching**

This is pretty much always a good idea.  After the first time a subject has been retrieved using `DeadboltHandler#getSubject`, the result will be cached for the remainder of the request.  If your view has a number of constraints, this gives a major performance gain.

    deadbolt {
        java {
            deadbolt.java.cache-user=true
        }
    }

**Profile your data layer**

Is it really taking > 1000ms to get the subject?  This is the root question.

**Comment by schaloner** [comment]
I think I was half-asleep when I wrote that reply.  Stand by for something more coherent.

**Comment by johdah** [comment]
I think the problem is on the database side. I haven't really figured out what param be going into jpaApi.em. So it's probably the database connection I can't get to work so I will have to try to solve that.

So it's deadbolt.java.cache-user, I had deadbolt.cache-user before. So I should change that?

**Comment by schaloner** [comment]
Yes - all properties are namespaced to the language-specific versions now.

**Comment by mkurz** [comment]
@johdah Maybe your problem has something to do with #7. A fix for it (#14) just got merged.
Try `2.4.0.1-SNAPSHOT` and add 
```
deadbolt.java.blocking=true
```
to `application.conf`

**Comment by johdah** [comment]
I saw that. I have added it to the code but I have a problem with JPA aswell so I need to fix that before I can test if this works.

**Comment by johdah** [comment]
I have this settings:

```
deadbolt {
  java {
    blocking = true # JPA doesn't support non-blocking
    cache-user = true # For the rest of the request
    handler = auth.MyDeadboltHandler
    view-timeout=130000 # Default 1000
  }
}
```

but I still get the following error:

```
2015-07-27 10:28:35,133 - [info] b.o.d.j.TemplateFailureListenerProvider - No custom TemplateFailureListener found, falling back to no-op implementation
2015-07-27 10:28:35,134 - [info] b.o.d.j.ViewSupport - Default timeout period for blocking views is [130000]ms
2015-07-27 10:28:35,204 - [error] application - 

! @6n0oe83ea - Internal server error, for (GET) [/] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[PromiseTimeoutException: Futures timed out after [1000 milliseconds]]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [play_2.11-2.4.2.jar:2.4.2]
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [play_2.11-2.4.2.jar:2.4.2]
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [play_2.11-2.4.2.jar:2.4.2]
Caused by: play.libs.F$PromiseTimeoutException: Futures timed out after [1000 milliseconds]
	at play.core.j.FPromiseHelper$.get(FPromiseHelper.scala:57) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.core.j.FPromiseHelper.get(FPromiseHelper.scala) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.libs.F$Promise.get(F.java:282) ~[play_2.11-2.4.2.jar:2.4.2]
	at be.objectify.deadbolt.java.actions.AbstractSubjectAction.execute(AbstractSubjectAction.java:81) ~[deadbolt-java_2.11-2.4.0.1-SNAPSHOT.jar:2.4.0.1-SNAPSHOT]
	at be.objectify.deadbolt.java.actions.AbstractDeadboltAction.call(AbstractDeadboltAction.java:109) ~[deadbolt-java_2.11-2.4.0.1-SNAPSHOT.jar:2.4.0.1-SNAPSHOT]
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [1000 milliseconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223) [scala-library-2.11.7.jar:na]
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190) ~[scala-library-2.11.7.jar:na]
	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:169) ~[akka-actor_2.11-2.3.11.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640) [scala-library-2.11.7.jar:na]

```

**Comment by schaloner** [comment]
The default timeout for blocking DB calls is 1000ms - this is unrelated to `view-timeout`.  You can change this with `deadbolt.java.blocking-timeout`, e.g.

    deadbolt {
      java {
        blocking = true # JPA doesn't support non-blocking
        cache-user = true # For the rest of the request
        handler = auth.MyDeadboltHandler
        view-timeout=130000 # Default 1000
        blocking-timeout=2000
      }
    }
