### ISSUE TITLE
ERROR on use comment routes and subject present

### ISSUE THREAD

**Issue by hideki22** [schaloner/deadbolt-2-java#53]
Hello,

Im getting an error when a user is not logged and go to protected route like subjectPresent or subjectNotPresent.

If i access to logging:

```
#deadbolt:subjectNotPresent
GET    /login                        controllers.UsersController.loginForm
#deadbolt:subjectNotPresent
POST   /login                        controllers.UsersController.login

```
And Im not logged, application say me:

```
[ERROR] [10/30/2017 08:20:00.116] [play-dev-mode-akka.actor.default-dispatcher-38] [akka.actor.ActorSystemImpl(play-dev-mode)] Internal server error, sending 500 response
java.util.NoSuchElementException: key not found: HandlerDef
	at scala.collection.immutable.Map$Map4.apply(Map.scala:187)
	at play.api.libs.typedmap.DefaultTypedMap.apply(TypedMap.scala:87)
	at play.libs.typedmap.TypedMap.get(TypedMap.java:48)
	at be.objectify.deadbolt.java.filters.DeadboltRouteCommentFilter.apply(DeadboltRouteCommentFilter.java:147)
	at play.mvc.Filter$1.apply(Filter.java:39)
	at play.api.mvc.Filter$$anon$1.apply(Filters.scala:61)
	at play.api.mvc.Filter$$anon$1.apply(Filters.scala:48)
	at play.api.mvc.EssentialAction$$anon$1.apply(Action.scala:37)
	at play.api.mvc.EssentialAction$$anon$1.apply(Action.scala:32)
	at play.core.server.AkkaHttpServer.$anonfun$executeHandler$1(AkkaHttpServer.scala:250)
	at play.api.mvc.EssentialAction$$anon$3.apply(Action.scala:48)
	at play.api.mvc.EssentialAction$$anon$3.apply(Action.scala:47)
	at play.core.server.AkkaHttpServer.executeAction(AkkaHttpServer.scala:284)
	at play.core.server.AkkaHttpServer.executeHandler(AkkaHttpServer.scala:254)
	at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:200)
	at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$3(AkkaHttpServer.scala:106)
	at akka.stream.impl.fusing.MapAsync$$anon$23.onPush(Ops.scala:1172)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:499)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:462)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:368)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:571)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:457)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:546)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:725)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:740)
	at akka.actor.Actor.aroundReceive(Actor.scala:514)
	at akka.actor.Actor.aroundReceive$(Actor.scala:512)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:650)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

but, I cant find the error in my class.... The filter are defined like your example:

```
/**
 * @author Steve Chaloner (steve@objectify.be)
 */
public class Filters implements HttpFilters {
    private final DeadboltRouteCommentFilter deadbolt;

    @Inject
    public Filters(final DeadboltRouteCommentFilter deadbolt) {
        this.deadbolt = deadbolt;
    }

    @Override
    public List<EssentialFilter> getFilters() {
        return Arrays.asList(deadbolt);
    }
}

```

What are doing wrong?

Thanks.

**Comment by mkurz** [comment]
@hideki22 Can you provide more information - like a simple example project where the error occurs so we can reproduce it?

**Comment by hideki22** [comment]
@mkurz I try, but i can reproduce it again, sorry. 
I think I have any config wrong in this moment.
In the moment of report bug, I used:

```
scala version  2.12.2
sbt version 0.13.15
play 2.6.3
deadbolt-java 2.6.1
```

But now, work ok.

You can close the bug.

Thank you.

**Comment by mkurz** [comment]
@hideki22 Thanks for you feedback. If the problem occurs again let us know :smile:
