### ISSUE TITLE
b.o.d.j.u.RequestUtils - Error getting subject: Futures timed out after [2000 milliseconds]

### ISSUE THREAD

**Issue by johdah** [schaloner/deadbolt-2-java#8]
I get this error all the time now.

I guess that it's caused by my getSubject method, but I have timed "Application.getLoggedOnUser()" and it takes  14-27ms so it couldn't be that I guess. So what could cause this?

```
2015-04-16 15:00:52,716 - [error] b.o.d.j.u.RequestUtils - Error getting subject: Futures timed out after [2000 milliseconds]
java.util.concurrent.TimeoutException: Futures timed out after [2000 milliseconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219) ~[org.scala-lang.scala-library-2.11.6.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223) ~[org.scala-lang.scala-library-2.11.6.jar:na]
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190) ~[org.scala-lang.scala-library-2.11.6.jar:na]
	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:169) ~[com.typesafe.akka.akka-actor_2.11-2.3.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640) [org.scala-lang.scala-library-2.11.6.jar:na]
```

My getSubject method looks like this.

```
public F.Promise<Subject> getSubject(Http.Context context) {
        return F.Promise.promise(new F.Function0<Subject>()
        {
            @Override
            public Subject apply() throws Throwable {
                return Application.getLoggedOnUser();
            }
        });
    }
```

**Comment by schaloner** [comment]
This is the reason I changed the signature of getSubject in 2.3.3 to return a Subject and not a promise.  You're using 2.3.2, I guess?

**Comment by johdah** [comment]
Yes, I will update. But I got the following error when rewriting the getSubject method.

```
[error] /home/johdah/Development/svn/MobitecAccess/branches/Johan/Hibernate/app/auth/MyDynamicResourceHandler.java:188: non-static method checkPatternEquality(be.objectify.deadbolt.core.models.Subject,java.lang.String) cannot be referenced from a static context
[error] DeadboltAnalyzer.checkPatternEquality
```

MyDynamicResourceHandler looks like this.

```java
	public boolean isAllowed(final String name, final String meta, final DeadboltHandler deadboltHandler, final Http.Context ctx) {
		final DynamicResourceHandler handler = HANDLERS.get(name);

//		return deadboltHandler.getSubject(ctx).map(
//			new F.Function<Subject, Boolean>() {
//				@Override
//				public Boolean apply(Subject subject) throws Throwable {
		if(meta.isEmpty()) return true;
		Subject subject = deadboltHandler.getSubject(ctx);

		// Check if permission pattern applied as meta is allowed!
		if(!DeadboltAnalyzer.checkPatternEquality(subject, meta)) {
			Logger.debug(String.format("Access failed to %s", meta));
			return false;
		}

		boolean result = false;
		if (handler == null) {
			Logger.error("No handler available for " + name);
		} else {
			result = handler.isAllowed(name, meta, deadboltHandler, ctx);
		}
		return result;
//				}
//			}
//		).get(1, TimeUnit.SECONDS);
	}
```

**Comment by schaloner** [comment]
DeadboltAnalyzer's methods are not static any more, because people were asking for DI support.  You can declare a static DeadboltAnalyzer in your MyDynamicResourceHandler class and reference that instead.

**Comment by johdah** [comment]
Thanks! Then it will hopefully work without the errors now then.

**Comment by schaloner** [comment]
No further issues reported on this topic.
